USE db_Biblioteca;

CREATE TABLE Autor (
IdAutor SMALLINT AUTO_INCREMENT PRIMARY KEY,
NomeAutor VARCHAR(50) NOT NULL,
SobrenomeAutor VARCHAR(60) NOT NULL
);

CREATE TABLE Assunto (
IdAssunto SMALLINT PRIMARY KEY AUTO_INCREMENT,
NomeAssunto VARCHAR(35) NOT NULL
);

CREATE TABLE Editora (
IdEditora SMALLINT PRIMARY KEY AUTO_INCREMENT,
NomeEditora VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Livro (
IdLivro SMALLINT AUTO_INCREMENT PRIMARY KEY,
NomeLivro VARCHAR(80) NOT NULL,
ISBN CHAR(13),
PrecoLivro DECIMAL(6,2) NOT NULL,
NumPaginas SMALLINT NOT NULL,
Edicao TINYINT,
DataPub DATE,
IdEditora SMALLINT NOT NULL,
IdAssunto SMALLINT NOT NULL,
CONSTRAINT fk_id_editora FOREIGN KEY (IdEditora)
 REFERENCES tbl_Editora(IdEditora)
 ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT fk_id_assunto FOREIGN KEY (IdAssunto)
 REFERENCES tbl_Assunto(IdAssunto)
 ON DELETE CASCADE ON UPDATE CASCADE
) AUTO_INCREMENT = 100;

CREATE TABLE LivroAutor (
IdAutor SMALLINT,
IdLivro SMALLINT,
CONSTRAINT pk_autor_livro PRIMARY KEY(IdAutor,IdLivro), # Chave Primária Composta
CONSTRAINT fk_id_autor FOREIGN KEY (IdAutor)
 REFERENCES tbl_Autor(IdAutor) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT fk_id_livro FOREIGN KEY (IdLivro)
 REFERENCES tbl_Livro(IdLivro) ON DELETE CASCADE ON UPDATE CASCADE
);